### ISSUE TITLE
Each Request tooks a Baseload of 30ms

### ISSUE THREAD

**Issue by Drolly666** [8ctopus/php-sandbox#1]
Hi there,

im a hobbyiest and my English is not the Best, sorry for that :)

Im writing a Rest-Api that tooks/return JSON-Data. For performance reasons, each Request is tested for Time its took.
Before i choose your Docker Image i used XAMPP for local testing. The Client testing my Restapi is Postmen.

Now i saw, that every Request tooks a minimum of 30ms for finishing, even, if the php script contains only a "exit()" call. I saw that before, only when xdebug is uesed in a special case. When the server has a medium idle-Time (a few minutes) the next Request tooks 2-4 Times longer than normal.

How i can prevent this ? Nice to hear from you. Thx.

Greets, Matthias

**Comment by 8ctopus** [comment]
hello Matthias,

Docker says that the performance is better if you use the WSL 2 engine, check your docker settings if you have that checkbox checked. Also consider disabling resource saver in the settings (I think that's what's causing requests to be slower after some idle time).

Now bear in mind that php-sandbox is a development environment and does not reflect the performance you will get in production. As for your actual 30ms timings, they are actually very fast compared to what I get on my computer (I get between 60 to 100ms).

In addition, you can use PHP SPX to find bottlenecks in your code (it's included in the README).
